version: '3.0'
services:
  app:
    container_name: 'weather_app'
    build:
      context: .
    env_file:
      - .env
    depends_on:
      postgres-service:
        condition: service_healthy
    ports:
      - '8000:8000'
    networks:
      - custom
    restart: on-failure

  postgres-service:
    container_name: 'postgres-service'
    image: postgres:14.7-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 10
    ports:
      - ${DB_PORT}:5432
    networks:
      - custom
networks:
  custom:
    driver: bridge