apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-app-deployment
  labels:
    app: store-app-deployment
spec:
  selector:
    matchLabels:
      app: store-app-deployment
  template:
    metadata:
      name: store-app-deployment
      labels:
        app: store-app-deployment      # service will connect by this labels
    spec:
      initContainers:
        - name: wait-for-postgres-db
          image: postgres:14.7-alpine
          imagePullPolicy: IfNotPresent
          command: [ 'sh', '-c', 'until pg_isready -h postgres-service -p 5432; do sleep 1; done;' ]
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASS
      containers:
        - name: store-app-deployment
          image: berezzin/store-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: app-secrets
      restartPolicy: Always

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: store-app-deployment-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: store-app-deployment
  minReplicas: 4
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: store-app-service
  labels:
    env: prod
spec:
  selector:
    app: store-app-deployment      # Selecting PODs with those Labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 80  # Port on Load Balancer
      targetPort: 8000  # Port on Pod
  type: ClusterIP